version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile-base
    container_name: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

  taskiq_worker:
    build:
      context: ./app
      dockerfile: Dockerfile-base
    container_name: taskiq_worker
    command: python -m taskiq_worker
    volumes:
      - ./app:/app
    depends_on:
      - redis

volumes:
  redis_data:
  mysql_data:
