"""empty message

Revision ID: 5c467baa75dd
Revises: 052cdd8b7f76
Create Date: 2024-08-14 15:05:00.956217

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c467baa75dd"
down_revision: Union[str, None] = "052cdd8b7f76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "created_at")
    # ### end Alembic commands ###
