"""empty message

Revision ID: 9b88e88dab03
Revises: 63cad359d504
Create Date: 2024-08-15 21:59:12.213478

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b88e88dab03"
down_revision: Union[str, None] = "63cad359d504"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("filename", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "filename")
    # ### end Alembic commands ###
